var chujingxuan = {};
chujingxuan.chujingxuan00 = {
    "data":{
		"pageStart":0,
		"pageSize":4,
		"count":72,
		"list":[{
            "sysId":1,
            "price_icon":"手机",
            "Img":"../IMG/buyimg/mobile1.png",
			"status":2
			},{
			"sysId":2,
            "price_icon":"壳膜线",
            "Img":"../IMG/buyimg/mobile2.png",
			"status":2
			},{
			"sysId":3,
            "price_icon":"其他配件",
            "Img":"../IMG/buyimg/mobile3.png",
			"status":2
			},{
			"sysId":4,
            "price_icon":"耳机音箱",
            "Img":"../IMG/buyimg/mobile4.png",
			"status":2
			}
		]
	}
},chujingxuan.chujingxuan01 = {
    "data":{
		"pageStart":0,
		"pageSize":3,
		"count":15,
		"list":[{
            "sysId":1,
            "price_icon":"百搭T恤",
            "Img":"../IMG/buyimg/yifu1.png",
			"status":2
			},{
			"sysId":2,
            "price_icon":"运动服饰",
            "Img":"../IMG/buyimg/yifu2.png",
			"status":2
			},{
			"sysId":3,
            "price_icon":"气质连衣裙",
            "Img":"../IMG/buyimg/yifu3.png",
			"status":2
			},{
			"sysId":4,
            "price_icon":"春夏上新",
            "Img":"../IMG/buyimg/yifu4.jpg",
			"status":2
			}
		]
	}
},chujingxuan.chujingxuan02 = {
    "data":{
		"pageStart":0,
		"pageSize":3,
		"count":15,
		"list":[{
            "sysId":1,
            "price_icon":"潮流男鞋",
            "Img":"../IMG/buyimg/bao1.png",
			"status":2
			},{
			"sysId":2,
            "price_icon":"潮流女鞋",
            "Img":"../IMG/buyimg/bao2.png",
			"status":2
			},{
			"sysId":3,
            "price_icon":"男包箱包",
            "Img":"../IMG/buyimg/bao3.png",
			"status":2
			},{
			"sysId":4,
            "price_icon":"时尚女包",
            "Img":"../IMG/buyimg/bao4.png",
			"status":2
			}
		]
	}
},chujingxuan.chujingxuan03 = {
    "data":{
		"pageStart":0,
		"pageSize":3,
		"count":15,
		"list":[{
            "sysId":1,
            "price_icon":"抽纸卷纸",
            "Img":"../IMG/buyimg/ri1.png",
			"status":2
			},{
			"sysId":2,
            "price_icon":"宠物生活",
            "Img":"../IMG/buyimg/ri2.png",
			"status":2
			},{
			"sysId":3,
            "price_icon":"清洁工具",
            "Img":"../IMG/buyimg/ri3.png",
			"status":2
			},{
			"sysId":4,
            "price_icon":"衣物清洁",
            "Img":"../IMG/buyimg/ri4.png",
			"status":2
			}
		]
	}
},chujingxuan.chujingxuan04 = {
    "data":{
		"pageStart":0,
		"pageSize":3,
		"count":15,
		"list":[{
            "sysId":1,
            "price_icon":"休闲零食",
            "Img":"../IMG/buyimg/shi1.png",
			"status":2
			},{
			"sysId":2,
            "price_icon":"饼干糕点",
            "Img":"../IMG/buyimg/shi2.png",
			"status":2
			},{
			"sysId":3,
            "price_icon":"酒水饮品",
            "Img":"../IMG/buyimg/shi3.png",
			"status":2
			},{
			"sysId":4,
            "price_icon":"粮油调味",
            "Img":"../IMG/buyimg/shi4.jpg",
			"status":2
			}
		]
	}
},chujingxuan.chujingxuan05 = {
    "data":{
		"pageStart":0,
		"pageSize":4,
		"count":72,
		"list":[{
            "sysId":1,
            "price_icon":"手机",
            "Img":"../IMG/buyimg/mobile1.png",
			"status":2
			},{
			"sysId":2,
            "price_icon":"壳膜线",
            "Img":"../IMG/buyimg/mobile2.png",
			"status":2
			},{
			"sysId":3,
            "price_icon":"其他配件",
            "Img":"../IMG/buyimg/mobile3.png",
			"status":2
			},{
			"sysId":4,
            "price_icon":"耳机音箱",
            "Img":"../IMG/buyimg/mobile4.png",
			"status":2
			}
		]
	}
},chujingxuan.chujingxuan06 = {
    "data":{
		"pageStart":0,
		"pageSize":3,
		"count":15,
		"list":[{
            "sysId":1,
            "price_icon":"百搭T恤",
            "Img":"../IMG/buyimg/yifu1.png",
			"status":2
			},{
			"sysId":2,
            "price_icon":"运动服饰",
            "Img":"../IMG/buyimg/yifu2.png",
			"status":2
			},{
			"sysId":3,
            "price_icon":"气质连衣裙",
            "Img":"../IMG/buyimg/yifu3.png",
			"status":2
			},{
			"sysId":4,
            "price_icon":"春夏上新",
            "Img":"../IMG/buyimg/yifu4.jpg",
			"status":2
			}
		]
	}
},chujingxuan.chujingxuan07 = {
    "data":{
		"pageStart":0,
		"pageSize":3,
		"count":15,
		"list":[{
            "sysId":1,
            "price_icon":"潮流男鞋",
            "Img":"../IMG/buyimg/bao1.png",
			"status":2
			},{
			"sysId":2,
            "price_icon":"潮流女鞋",
            "Img":"../IMG/buyimg/bao2.png",
			"status":2
			},{
			"sysId":3,
            "price_icon":"男包箱包",
            "Img":"../IMG/buyimg/bao3.png",
			"status":2
			},{
			"sysId":4,
            "price_icon":"时尚女包",
            "Img":"../IMG/buyimg/bao4.png",
			"status":2
			}
		]
	}
},chujingxuan.chujingxuan08 = {
    "data":{
		"pageStart":0,
		"pageSize":3,
		"count":15,
		"list":[{
            "sysId":1,
            "price_icon":"抽纸卷纸",
            "Img":"../IMG/buyimg/ri1.png",
			"status":2
			},{
			"sysId":2,
            "price_icon":"宠物生活",
            "Img":"../IMG/buyimg/ri2.png",
			"status":2
			},{
			"sysId":3,
            "price_icon":"清洁工具",
            "Img":"../IMG/buyimg/ri3.png",
			"status":2
			},{
			"sysId":4,
            "price_icon":"衣物清洁",
            "Img":"../IMG/buyimg/ri4.png",
			"status":2
			}
		]
	}
},chujingxuan.chujingxuan09 = {
    "data":{
		"pageStart":0,
		"pageSize":3,
		"count":15,
		"list":[{
            "sysId":1,
            "price_icon":"休闲零食",
            "Img":"../IMG/buyimg/shi1.png",
			"status":2
			},{
			"sysId":2,
            "price_icon":"饼干糕点",
            "Img":"../IMG/buyimg/shi2.png",
			"status":2
			},{
			"sysId":3,
            "price_icon":"酒水饮品",
            "Img":"../IMG/buyimg/shi3.png",
			"status":2
			},{
			"sysId":4,
            "price_icon":"粮油调味",
            "Img":"../IMG/buyimg/shi4.jpg",
			"status":2
			}
		]
	}
},chujingxuan.chujingxuan010 = {
    "data":{
		"pageStart":0,
		"pageSize":3,
		"count":15,
		"list":[{
            "sysId":1,
            "price_icon":"抽纸卷纸",
            "Img":"../IMG/buyimg/ri1.png",
			"status":2
			},{
			"sysId":2,
            "price_icon":"宠物生活",
            "Img":"../IMG/buyimg/ri2.png",
			"status":2
			},{
			"sysId":3,
            "price_icon":"清洁工具",
            "Img":"../IMG/buyimg/ri3.png",
			"status":2
			},{
			"sysId":4,
            "price_icon":"衣物清洁",
            "Img":"../IMG/buyimg/ri4.png",
			"status":2
			}
		]
	}
},chujingxuan.chujingxuan011 = {
    "data":{
		"pageStart":0,
		"pageSize":3,
		"count":15,
		"list":[{
            "sysId":1,
            "price_icon":"休闲零食",
            "Img":"../IMG/buyimg/shi1.png",
			"status":2
			},{
			"sysId":2,
            "price_icon":"饼干糕点",
            "Img":"../IMG/buyimg/shi2.png",
			"status":2
			},{
			"sysId":3,
            "price_icon":"酒水饮品",
            "Img":"../IMG/buyimg/shi3.png",
			"status":2
			},{
			"sysId":4,
            "price_icon":"粮油调味",
            "Img":"../IMG/buyimg/shi4.jpg",
			"status":2
			}
		]
	}
},chujingxuan.chujingxuan012 = {
    "data":{
		"pageStart":0,
		"pageSize":3,
		"count":15,
		"list":[{
            "sysId":1,
            "price_icon":"潮流男鞋",
            "Img":"../IMG/buyimg/bao1.png",
			"status":2
			},{
			"sysId":2,
            "price_icon":"潮流女鞋",
            "Img":"../IMG/buyimg/bao2.png",
			"status":2
			},{
			"sysId":3,
            "price_icon":"男包箱包",
            "Img":"../IMG/buyimg/bao3.png",
			"status":2
			},{
			"sysId":4,
            "price_icon":"时尚女包",
            "Img":"../IMG/buyimg/bao4.png",
			"status":2
			}
		]
	}
},chujingxuan.chujingxuan013 = {
    "data":{
		"pageStart":0,
		"pageSize":3,
		"count":15,
		"list":[{
            "sysId":1,
            "price_icon":"抽纸卷纸",
            "Img":"../IMG/buyimg/ri1.png",
			"status":2
			},{
			"sysId":2,
            "price_icon":"宠物生活",
            "Img":"../IMG/buyimg/ri2.png",
			"status":2
			},{
			"sysId":3,
            "price_icon":"清洁工具",
            "Img":"../IMG/buyimg/ri3.png",
			"status":2
			},{
			"sysId":4,
            "price_icon":"衣物清洁",
            "Img":"../IMG/buyimg/ri4.png",
			"status":2
			}
		]
	}
},chujingxuan.chujingxuan014 = {
    "data":{
		"pageStart":0,
		"pageSize":3,
		"count":15,
		"list":[{
            "sysId":1,
            "price_icon":"休闲零食",
            "Img":"../IMG/buyimg/shi1.png",
			"status":2
			},{
			"sysId":2,
            "price_icon":"饼干糕点",
            "Img":"../IMG/buyimg/shi2.png",
			"status":2
			},{
			"sysId":3,
            "price_icon":"酒水饮品",
            "Img":"../IMG/buyimg/shi3.png",
			"status":2
			},{
			"sysId":4,
            "price_icon":"粮油调味",
            "Img":"../IMG/buyimg/shi4.jpg",
			"status":2
			}
		]
	}
},chujingxuan.chujingxuan015 = {
    "data":{
		"pageStart":0,
		"pageSize":3,
		"count":15,
		"list":[{
            "sysId":1,
            "price_icon":"抽纸卷纸",
            "Img":"../IMG/buyimg/ri1.png",
			"status":2
			},{
			"sysId":2,
            "price_icon":"宠物生活",
            "Img":"../IMG/buyimg/ri2.png",
			"status":2
			},{
			"sysId":3,
            "price_icon":"清洁工具",
            "Img":"../IMG/buyimg/ri3.png",
			"status":2
			},{
			"sysId":4,
            "price_icon":"衣物清洁",
            "Img":"../IMG/buyimg/ri4.png",
			"status":2
			}
		]
	}
},chujingxuan.chujingxuan016 = {
    "data":{
		"pageStart":0,
		"pageSize":3,
		"count":15,
		"list":[{
            "sysId":1,
            "price_icon":"休闲零食",
            "Img":"../IMG/buyimg/shi1.png",
			"status":2
			},{
			"sysId":2,
            "price_icon":"饼干糕点",
            "Img":"../IMG/buyimg/shi2.png",
			"status":2
			},{
			"sysId":3,
            "price_icon":"酒水饮品",
            "Img":"../IMG/buyimg/shi3.png",
			"status":2
			},{
			"sysId":4,
            "price_icon":"粮油调味",
            "Img":"../IMG/buyimg/shi4.jpg",
			"status":2
			}
		]
	}
},chujingxuan.chujingxuan017 = {
    "data":{
		"pageStart":0,
		"pageSize":3,
		"count":15,
		"list":[{
            "sysId":1,
            "price_icon":"抽纸卷纸",
            "Img":"../IMG/buyimg/ri1.png",
			"status":2
			},{
			"sysId":2,
            "price_icon":"宠物生活",
            "Img":"../IMG/buyimg/ri2.png",
			"status":2
			},{
			"sysId":3,
            "price_icon":"清洁工具",
            "Img":"../IMG/buyimg/ri3.png",
			"status":2
			},{
			"sysId":4,
            "price_icon":"衣物清洁",
            "Img":"../IMG/buyimg/ri4.png",
			"status":2
			}
		]
	}
}