var pingouDate = {};
pingouDate.pingouDate00= {
    "data":{
		"pageStart":0,
		"pageSize":3,
		"count":15,
		"list":[{
            "sysId":1,
            "price_icon":"￥",
            "sub_title1":"2人拼",
            "sub_title2":"9",
            "sub_title3":".80",
            "sub_title4":"已有608人拼",
            "Img":"../IMG/buyimg/pin1.dpg",
			"status":2
			},{
			"sysId":2,
            "price_icon":"￥",
            "sub_title1":"2人拼",
            "sub_title2":"21",
            "sub_title3":".80",
            "sub_title4":"已有2.2万人拼",
            "Img":"../IMG/buyimg/pin2.webp.jpg",
			"status":2
			},{
			"sysId":3,
            "price_icon":"￥",
            "sub_title1":"2人拼",
            "sub_title2":"7",
            "sub_title3":".90",
            "sub_title4":"已有7970人拼",
            "Img":"../IMG/buyimg/pin3.webp.jpg",
			"status":2
			}
		]
	}
},pingouDate.pingouDate01= {
    "data":{
		"pageStart":0,
		"pageSize":3,
		"count":15,
		"list":[{
            "sysId":1,
            "price_icon":"￥",
            "sub_title1":"2人拼",
            "sub_title2":"9",
            "sub_title3":".80",
            "sub_title4":"已有608人拼",
            "Img":"../IMG/buyimg/pin4webp.webp.jpg",
			"status":2
			},{
			"sysId":2,
            "price_icon":"￥",
            "sub_title1":"2人拼",
            "sub_title2":"21",
            "sub_title3":".80",
            "sub_title4":"已有2.2万人拼",
            "Img":"../IMG/buyimg/pin5.webp.jpg",
			"status":2
			},{
			"sysId":3,
            "price_icon":"￥",
            "sub_title1":"2人拼",
            "sub_title2":"7",
            "sub_title3":".90",
            "sub_title4":"已有7970人拼",
            "Img":"../IMG/buyimg/pin6.webp.jpg",
			"status":2
			}
		]
	}
},pingouDate.pingouDate02= {
    "data":{
		"pageStart":0,
		"pageSize":3,
		"count":15,
		"list":[{
            "sysId":1,
            "price_icon":"￥",
            "sub_title1":"2人拼",
            "sub_title2":"9",
            "sub_title3":".80",
            "sub_title4":"已有608人拼",
            "Img":"../IMG/buyimg/pin2.webp.jpg",
			"status":2
			},{
			"sysId":2,
            "price_icon":"￥",
            "sub_title1":"2人拼",
            "sub_title2":"21",
            "sub_title3":".80",
            "sub_title4":"已有2.2万人拼",
            "Img":"../IMG/buyimg/pin5.webp.jpg",
			"status":2
			},{
			"sysId":3,
            "price_icon":"￥",
            "sub_title1":"2人拼",
            "sub_title2":"7",
            "sub_title3":".90",
            "sub_title4":"已有7970人拼",
            "Img":"../IMG/buyimg/pin7.webp.jpg",
			"status":2
			}
		]
	}
},pingouDate.pingouDate03= {
    "data":{
		"pageStart":0,
		"pageSize":3,
		"count":15,
		"list":[{
            "sysId":1,
            "price_icon":"￥",
            "sub_title1":"2人拼",
            "sub_title2":"9",
            "sub_title3":".80",
            "sub_title4":"已有608人拼",
            "Img":"../IMG/buyimg/pin5.webp.jpg",
			"status":2
			},{
			"sysId":2,
            "price_icon":"￥",
            "sub_title1":"2人拼",
            "sub_title2":"21",
            "sub_title3":".80",
            "sub_title4":"已有2.2万人拼",
            "Img":"../IMG/buyimg/pin1.dpg",
			"status":2
			},{
			"sysId":3,
            "price_icon":"￥",
            "sub_title1":"2人拼",
            "sub_title2":"7",
            "sub_title3":".90",
            "sub_title4":"已有7970人拼",
            "Img":"../IMG/buyimg/pin6.webp.jpg",
			"status":2
			}
		]
	}
},pingouDate.pingouDate04= {
    "data":{
		"pageStart":0,
		"pageSize":3,
		"count":15,
		"list":[{
            "sysId":1,
            "price_icon":"￥",
            "sub_title1":"2人拼",
            "sub_title2":"9",
            "sub_title3":".80",
            "sub_title4":"已有608人拼",
            "Img":"../IMG/buyimg/pin3.webp.jpg",
			"status":2
			},{
			"sysId":2,
            "price_icon":"￥",
            "sub_title1":"2人拼",
            "sub_title2":"21",
            "sub_title3":".80",
            "sub_title4":"已有2.2万人拼",
            "Img":"../IMG/buyimg/pin5.webp.jpg",
			"status":2
			},{
			"sysId":3,
            "price_icon":"￥",
            "sub_title1":"2人拼",
            "sub_title2":"7",
            "sub_title3":".90",
            "sub_title4":"已有7970人拼",
            "Img":"../IMG/buyimg/pin6.webp.jpg",
			"status":2
			}
		]
	}
}